version: "3.4"
services:
 vite_docker:
   image: node:alpine
   container_name: vite_docker
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /app
   volumes:
     - type: bind
       source: ./
       target: /app
   tty: true